name: Update.luci-app-alist
on: 
  repository_dispatch:
  workflow_dispatch:

# 定时触发编译
#  schedule:
#    - cron: 0 22 * * *

# 点赞☆Star触发编译
#  watch:
#    types: [started]

jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
    - name: Clone Repository
      uses: actions/checkout@v4

    - name: Set git
      run : |
        git config --global user.email "194788255+Jaykwok2999@users.noreply.github.com"
        git config --global user.name "Jaykwok2999"
        sudo timedatectl set-timezone "Asia/Shanghai"

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      continue-on-error: true
      with:
        retain_days: 1
        keep_minimum_runs: 0  
        
    - name: Update.luci-app-alist
      run: |

        rm -rf ./alist
        rm -rf ./luci-app-alist
         
        git clone https://github.com/immortalwrt/packages.git -b openwrt-24.10
        mv ./packages/net/alist  ./alist
        rm -rf ./packages/net
        git clone https://github.com/immortalwrt/luci.git -b openwrt-24.10
        mv ./luci/applications/luci-app-alist ./luci-app-alist
        rm -rf ./luci/applications
        rm -rf ./packages
        rm -rf ./luci
        sed -i 's/services/nas/g' luci-app-alist/root/usr/share/luci/menu.d/luci-app-alist.json
        sed -i 's/msgstr "AList"/msgstr "AList文件列表"/g' luci-app-alist/po/zh_Hans/alist.po
        sed -i 's/msgstr "AList"/msgstr "AList文件列表"/g' luci-app-alist/po/zh_Hant/alist.po
        
    - name: Apply
      run: |
        Emoji=("🎉" "🤞" "✨" "🎁" "🎈" "🎄" "🎨" "💋" "🍓" "🍕" "🍉" "💐" "🌴" "🚀" "🛸" "🗽" "⛅" "🌈" "🔥" "⛄" "🐶" "🏅" "🦄" "🐤")
        git add .
        git commit -m "${Emoji[$[$RANDOM % ${#Emoji[@]}]]} Sync $(date +%Y-%m-%d" "%H:%M:%S)"
        for pkg in $(git diff-tree --no-commit-id --name-only HEAD); do
          if [ "$(grep "PKG_RELEASE" $pkg/Makefile)" ]; then
            sed -i "s/PKG_RELEASE:=.*/PKG_RELEASE:=$(git rev-list --count main $pkg)/" $pkg/Makefile || true
          fi
        done
        git reset --soft HEAD^
        git add .
        git commit -m "${Emoji[$[$RANDOM % ${#Emoji[@]}]]} Sync $(date +%Y-%m-%d" "%H:%M:%S)"
        git push -f
